language: rust
rust:
        - stable
        - beta
        - nightly
matrix:
        allow_failures:
                - rust: nightly
install: contrib/travis-install-deps.sh
script: contrib/travis-run.sh
cache:
        directories:
                - deps
addons:
        apt:
                packages:
                        - cmake
                        - libcurl4-openssl-dev
                        - libelf-dev
                        - libdw-dev
after_success: contrib/travis-kcov.sh
