install:
# Need Mingw to build C bits
- SET PATH=%PATH%;C:\MinGW\bin
# rust-crypto needs these flags when using 32bit Mingw
- SET CFLAGS=-mmmx -msse
- ps: Start-FileDownload http://static.rust-lang.org/dist/$env:PLATFORM -FileName rust.exe
- rust.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
- SET PATH=%PATH%;C:\Program Files\Rust\bin
- rustc -vV
- cargo -V
- set RUST_BACKTRACE=1
# Get libressl binary build
- appveyor DownloadFile http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.3.1-windows.zip
- 7z x libressl-2.3.1-windows.zip
- set LIBTLS_LIBRARY_PATH=%cd%\libressl-2.3.1-windows\x86\
- set LIBTLS_INCLUDE_PATH=%cd%\libressl-2.3.1-windows\include\
- set LIBTLS_LIBS=libtls-9;ws2_32
- set PATH=%LIBTLS_LIBRARY_PATH%;%PATH%
- openssl version
platform:
- rust-1.6.0-i686-pc-windows-gnu.exe
- rust-beta-i686-pc-windows-gnu.exe
# To build against multiple rust versions add them here
build: false
test_script:
- cargo test --verbose --manifest-path telos/Cargo.toml
